### ISSUE TITLE
i'm getting exception

### ISSUE THREAD

**Issue by jhon23xx** [adeoy/FacebookPostsScraper#1]
raise Exception('Redirect Url not found')
Exception: Redirect Url not found

**Comment by hhsm95** [comment]
Hi, check if you can log without problems to your Facebook account. This exception happens when it logs in but asks for a security question.

**Comment by hhsm95** [comment]
In the latest commit the exception message explains that you need to log in desktop Facebook to restart your password. After that now you can log in again.
